const products = [
  {id:1,type:'Bone plate',category:'plates',name:'Feline / small canine T-plate',sku:'NSS-TP-2418',desc:'2.4 mm · 18 hole · Left',price:148,stock:12,location:'A-12 · Bay 04',compat:'Cats, toy & small breed dogs',procedure:'Radial / ulnar fracture',image:'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=800&q=80'},
  {id:2,type:'Bone plate',category:'plates',name:'Locking compression plate',sku:'NSS-LCP-3012',desc:'3.0 mm · 12 hole · Straight',price:196,stock:7,location:'A-08 · Bay 02',compat:'Small & medium breed dogs',procedure:'Radius, ulna & tibia',image:'https://images.unsplash.com/photo-1553882809-a4f57e1439a2?auto=format&fit=crop&w=800&q=80'},
  {id:3,type:'Cortical screw',category:'screws',name:'Self-tapping cortical screws',sku:'NSS-CS-2420',desc:'2.4 mm · 20 pack · Titanium',price:62,stock:48,location:'B-03 · Drawer 18',compat:'Universal · 2.4 mm systems',procedure:'Plate fixation',image:'https://images.unsplash.com/photo-1584467735871-1f7f3d80f5a4?auto=format&fit=crop&w=800&q=80'},
  {id:4,type:'Procedure kit',category:'kits',name:'TPLO small / medium kit',sku:'NSS-TPLO-SM',desc:'Blade, plate & screw set',price:385,stock:3,location:'K-01 · Ready shelf',compat:'Dogs 10–25 kg',procedure:'Tibial plateau leveling',image:'https://images.unsplash.com/photo-1599443015574-b831e7b13a9b?auto=format&fit=crop&w=800&q=80'},
  {id:5,type:'K-wire',category:'pins',name:'Trocar-point K-wire set',sku:'NSS-KW-1610',desc:'1.6 mm · 10 pack · Sterile',price:84,stock:19,location:'C-06 · Drawer 03',compat:'Cats & dogs',procedure:'Fracture stabilization',image:'https://images.unsplash.com/photo-1638202993928-7d113b8a6e6d?auto=format&fit=crop&w=800&q=80'},
  {id:6,type:'Bone plate',category:'plates',name:'TPLO locking plate',sku:'NSS-TL-3020',desc:'3.0 mm · Right · Medium',price:229,stock:2,location:'A-10 · Bay 01',compat:'Medium breed dogs 15–30 kg',procedure:'Tibial plateau leveling',image:'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=800&q=80'}
];
const orderHistory = [{id:'OO-240821-18',date:'21 Aug 2026 · 09:42',items:'TPLO locking plate + 4 items',status:'Awaiting pickup',total:'$462.00'},{id:'OO-240817-07',date:'17 Aug 2026 · 14:16',items:'Radial fracture set · 7 items',status:'Ready for pickup',total:'$318.00',ready:true},{id:'OO-240802-31',date:'02 Aug 2026 · 11:08',items:'Cortical screws · 2 packs',status:'Completed',total:'$124.00',ready:true}];
let cart = []; let activeCategory = 'all';
const $ = (selector) => document.querySelector(selector);
function money(value){return `$${value.toFixed(2)}`}
function renderProducts(){
  const query = $('#search-input').value.toLowerCase();
  let visible = products.filter(p => (activeCategory==='all'||p.category===activeCategory) && `${p.name} ${p.sku} ${p.procedure} ${p.compat}`.toLowerCase().includes(query));
  const sort=$('#sort-select').value; if(sort==='stock') visible.sort((a,b)=>b.stock-a.stock); if(sort==='price-low') visible.sort((a,b)=>a.price-b.price);
  $('#result-count').textContent=`Showing ${visible.length} product${visible.length===1?'':'s'}`;
  $('#product-grid').innerHTML=visible.length ? visible.map(productCard).join('') : `<div class="rail-empty"><div>⌕</div><p>No hardware matches that search.</p><small>Try a different procedure, SKU, or category.</small></div>`;
  document.querySelectorAll('.product-card').forEach(card=>card.addEventListener('click',()=>openDetail(Number(card.dataset.id))));
  document.querySelectorAll('.add-btn').forEach(btn=>btn.addEventListener('click',event=>{event.stopPropagation();addToCart(Number(btn.dataset.id))}));
}
function productCard(p){return `<article class="product-card" data-id="${p.id}"><div class="product-visual"><img src="${p.image}" alt="${p.name}"/><span class="stock-badge ${p.stock<4?'low':''}">${p.stock<4?'Only '+p.stock+' left':p.stock+' in stock'}</span></div><div class="product-info"><span class="product-type">${p.type} · ${p.sku}</span><h3>${p.name}</h3><p>${p.desc} · ${p.compat}</p><div class="product-bottom"><div><b>${money(p.price)}</b><small>per unit · ${p.location}</small></div><button class="add-btn" data-id="${p.id}" aria-label="Add ${p.name} to order">＋</button></div></div></article>`}
function addToCart(id){const item=cart.find(i=>i.id===id); if(item)item.qty++; else cart.push({id,qty:1}); renderCart(); showToast('Added to your order');}
function renderCart(){const count=cart.reduce((sum,i)=>sum+i.qty,0); const total=cart.reduce((sum,i)=>{const p=products.find(x=>x.id===i.id);return sum+p.price*i.qty},0); $('#cart-count').textContent=count; $('#rail-title').textContent=count?`${count} item${count===1?'':'s'} selected`:'Nothing added yet'; $('#rail-total').textContent=money(total); $('#review-btn').disabled=!count; $('#rail-items').innerHTML=count?cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="rail-line"><div><b>${p.name}</b><small>${i.qty} × ${money(p.price)}</small></div><span>${money(i.qty*p.price)}</span></div>`}).join(''):`<div class="rail-empty"><div>＋</div><p>Add hardware to start building your order.</p><small>We’ll check availability as you go.</small></div>`;}
function openDetail(id){const p=products.find(x=>x.id===id); $('#detail-content').innerHTML=`<div class="detail-wrap"><div class="detail-image"><img src="${p.image}" alt="${p.name}"/></div><div class="detail-copy"><span class="product-type">${p.type} · ${p.sku}</span><h2>${p.name}</h2><p>${p.desc}. Designed for predictable placement and reliable fixation in small animal orthopedic procedures.</p><div class="spec-grid"><div><small>Available now</small><b>${p.stock} units</b></div><div><small>Warehouse location</small><b>${p.location}</b></div><div><small>Material</small><b>Titanium alloy</b></div><div><small>Lead time</small><b>Same-day pickup</b></div></div><div class="compatibility"><b>Compatibility</b><br/>${p.compat}. Commonly used for ${p.procedure.toLowerCase()}.</div><div class="detail-buy"><strong>${money(p.price)} <small>/ unit</small></strong><div class="stepper"><button id="detail-minus">−</button><span id="detail-qty">1</span><button id="detail-plus">＋</button></div><button class="primary-btn" id="detail-add">Add to order <span>→</span></button></div></div></div>`; $('#detail-modal').classList.add('open'); let qty=1; $('#detail-minus').onclick=()=>{qty=Math.max(1,qty-1);$('#detail-qty').textContent=qty};$('#detail-plus').onclick=()=>{qty=Math.min(p.stock,qty+1);$('#detail-qty').textContent=qty};$('#detail-add').onclick=()=>{for(let n=0;n<qty;n++)addToCart(id);$('#detail-modal').classList.remove('open')};}
function openReview(){if(!cart.length)return; $('#review-items').innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="review-line"><div><b>${p.name}</b><small>${p.sku} · ${i.qty} unit${i.qty>1?'s':''}</small></div><strong>${money(p.price*i.qty)}</strong></div>`}).join('');$('#review-total').textContent=$('#rail-total').textContent;$('#review-modal').classList.add('open');}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
function renderOrders(){ $('#orders-list').innerHTML=orderHistory.map(o=>`<div class="order-row"><div><b>${o.id}</b><small>${o.date}</small></div><div><small>Order contents</small><b>${o.items}</b></div><div><small>Status</small><span class="status ${o.ready?'ready':''}">${o.status}</span></div><div class="order-price"><small>Total</small><b>${o.total}</b></div><button class="text-btn">View →</button></div>`).join('');}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$('#'+view+'-view').classList.add('active-view');document.querySelectorAll('.nav-item[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='orders')renderOrders()}
document.querySelectorAll('.nav-item[data-view]').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view)));document.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{activeCategory=chip.dataset.filter;document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));chip.classList.add('active');renderProducts()}));$('#search-input').addEventListener('input',renderProducts);$('#sort-select').addEventListener('change',renderProducts);$('#review-btn').addEventListener('click',openReview);document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.modal-backdrop').classList.remove('open')));document.querySelectorAll('.modal-backdrop').forEach(backdrop=>backdrop.addEventListener('click',e=>{if(e.target===backdrop)backdrop.classList.remove('open')}));$('#submit-order').addEventListener('click',()=>{if(!$('#case-reference').value.trim()){showToast('Please add a patient or case reference');$('#case-reference').focus();return}$('#review-modal').classList.remove('open');const orderId=`OO-${Math.floor(Math.random()*900000+100000)}`;cart=[];renderCart();showToast(`Order ${orderId} placed successfully`);setTimeout(()=>switchView('orders'),600)});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#search-input').focus()}if(e.key==='Escape')document.querySelectorAll('.modal-backdrop.open').forEach(m=>m.classList.remove('open'))});renderProducts();renderCart();